name: github-actions-for-flutter-manual
on:
  workflow_dispatch:
    inputs:
      androidKeystorePassword:
        description: 'Android Keystore Password'     
        required: true
      androidKeystoreAlias:
        description: 'Android Keystore Alias'
        required: true
      androidKeystorePrivateKeyPassword:
        description: 'Android Keystore Private Key Password'
        required: true
      firebaseToken:
        description: 'Firebase Token'
        required: true
      firebaseAndroidAppId:
        description: 'Firebase Android App ID'
        required: true

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart *.freezed.dart" # defaults to "" (none)
      flutter_channel: stable # defaults to (stable)
      flutter_version: 2.8.1 # defaults to latest version
      working_directory: "." # defaults to "." (the top-level directory)
  
  deploy-job:
    runs-on: ubuntu-latest
    name: Deploy Flutter app
    steps:
    - name: Print Android Keystore Password
      run: |
        echo "Android Keystore Password: ${{ github.event.inputs.androidKeystorePassword }}"
