name: github-actions-for-flutter
on:
  push:
    paths:
      - "**.dart"
  pull_request:
    paths:
      - "**.dart"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart *.freezed.dart" # defaults to "" (none)
      flutter_channel: stable # defaults to (stable)
      flutter_version: 2.8.1 # defaults to latest version
      working_directory: "." # defaults to "." (the top-level directory)
